---
title: "DC"
author: "Bill Lang"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
DC <- read.csv("C:/Users/the36/Desktop/DataRA/hiphop_insyle/hiphop_dc.csv")
DC <- DC %>% filter(ï..Transcriber != "")
DC
```

```{r}
DC <- DC %>% 
  #select(Year, Column, Area, Street, Hse.No) %>% 
  mutate(Column = tolower(Column)) %>% 
  mutate(Area = tolower(Area)) %>% 
  mutate(Street = tolower(Street)) %>% 
  mutate(Price.type = tolower(Price.type))

```

```{r}
DC <- DC %>% unite(Address, Street:Hse.No, sep = " ") 

DC$Address <- trimws(DC$Address, which = c("right"))

DC$Area <- trimws(DC$Area, which = c("right"))

DC
```


```{r}
data <- DC %>% group_by(Area) %>% 
  summarise(
    count = n()
  ) %>% arrange(desc(count)) 

data

sum(data$count)

data2 <- data %>% filter(Area != "")
sum(data2$count[1:935])
```

```{r}
excelDC <- DC %>% mutate(Area2 = ifelse(grepl(paste(data2$Area[1:935],collapse="|"), Area), as.character(Area), 1))
excelDC %>% filter(Area2 == 1)
```
```{r}
excelDC %>% filter(Price.type == "")
```









```{r}
DC %>% filter(Area == "")

DC %>% filter(Area == "" & Address != "")
```







DC objective: create a new column with the default state being D.C. and reassign that column with either Virginia or Maryland.



```{r}
DC

DC2 <- DC %>% mutate(State = "DC")

DC3 <- DC2 %>% mutate(State = ifelse(grepl("virginia", Column, ignore.case = TRUE), "VA",   
              ifelse(grepl("virginia", Area, ignore.case = TRUE), "VA", 
              ifelse(grepl("virginia", Street, ignore.case = TRUE), "VA",
              ifelse(grepl("virginia", Hse.No, ignore.case = TRUE), "VA", "DC")))))
DC3

DC3 %>% group_by(State) %>% 
  summarise(count = n())


DC4 <- DC3 %>% mutate(State = ifelse(grepl("maryland", Column, ignore.case = TRUE), "MA",   
              ifelse(grepl("maryland", Area, ignore.case = TRUE), "MA", 
              ifelse(grepl("maryland", Street, ignore.case = TRUE), "MA", 
              ifelse(grepl("maryland", Hse.No, ignore.case = TRUE), "MA", as.character(State))))))
DC4

DC4 %>% group_by(State) %>% 
  summarise(count = n())


```

```{r}
write.csv(DC4, file = "C:/Users/the36/Desktop/DC/DCWithState.csv")
```






















Area can maybe be used but is missing a lot.
Column in useless.

```{r}

DC$Column <- trimws(DC$Column, which = c("right"))

data <- DC %>% group_by(Column) %>% 
  summarise(
    count = n()
  ) %>% arrange(desc(count)) 

data

sum(data$count)

sum(data$count[1:20])

```
