---
title: "Excel Sheet Update"
author: "Bill Lang"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

This function takes in a dataframe with the year and the column of the geographic indicator and stratifies by decade. It produces a list of three objects a list with the the totals by decade, the total number categorized, and the total number of observations in the data. 


```{r}
totalRentOrOwn <- function(dataFrame, year, column, priceColumn){

dataFrame <- dataFrame %>% mutate(priceColumn = tolower(priceColumn))  
  
the1890s <- c(1890:1899)
the1900s <- c(1900:1909)
the1910s <- c(1910:1919)
the1920s <- c(1920:1929)
the1930s <- c(1930:1939)
the1940s <- c(1940:1949)
the1950s <- c(1950:1959)
the1960s <- c(1960:1969)
the1970s <- c(1970:1979)
the1980s <- c(1980:1989)
the1990s <- c(1990:1999)

dataYears <- dataFrame %>% 
  mutate(groupYear = ifelse(grepl(paste(the1890s,collapse="|"), Year, ignore.case = TRUE), 1890, 
              ifelse(grepl(paste(the1900s,collapse="|"), Year, ignore.case = TRUE), 1900, 
              ifelse(grepl(paste(the1910s,collapse="|"), Year, ignore.case = TRUE), 1910, 
              ifelse(grepl(paste(the1920s,collapse="|"), Year, ignore.case = TRUE), 1920,
              ifelse(grepl(paste(the1930s,collapse="|"), Year, ignore.case = TRUE), 1930, 
              ifelse(grepl(paste(the1940s,collapse="|"), Year, ignore.case = TRUE), 1940,
              ifelse(grepl(paste(the1950s,collapse="|"), Year, ignore.case = TRUE), 1950,
              ifelse(grepl(paste(the1960s,collapse="|"), Year, ignore.case = TRUE), 1960,
              ifelse(grepl(paste(the1970s,collapse="|"), Year, ignore.case = TRUE), 1970,
              ifelse(grepl(paste(the1980s,collapse="|"), Year, ignore.case = TRUE), 1980,
              ifelse(grepl(paste(the1990s,collapse="|"), Year, ignore.case = TRUE), 1990, "???"))))))))))))

dataSummaryRent <- dataYears %>% mutate(rentDummy = ifelse(priceColumn == "rent", 1, 0)) %>% group_by(groupYear) %>% summarise(rentYearTotals = sum(rentDummy))
dataSummaryOwn <- dataYears %>% mutate(ownDummy = ifelse(priceColumn == "sale", 1, 0)) %>% group_by(groupYear) %>% summarise(ownYearTotals = sum(ownDummy))
totalObservations <- dim(dataFrame)[1]

df <- cbind.data.frame(dataSummaryRent[,2], dataSummaryOwn[,2], dataSummaryRent[,2] + dataSummaryOwn[,2],totalObservations)
colnames(df)[3] <- "yearObsTotal"
rownames(df) <- c(1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990)

return(df)
}
```

```{r}
test <- totalRentOrOwn(dataMutc, dataMutc$Year, priceColumn = dataMutc$Price.type)
test
```


```{r}
excelDataFound <- function(dataFrame, year, column, priceColumn) {
  
dataFrame <- dataFrame %>% mutate(priceColumn = tolower(priceColumn))

the1890s <- c(1890:1899)
the1900s <- c(1900:1909)
the1910s <- c(1910:1919)
the1920s <- c(1920:1929)
the1930s <- c(1930:1939)
the1940s <- c(1940:1949)
the1950s <- c(1950:1959)
the1960s <- c(1960:1969)
the1970s <- c(1970:1979)
the1980s <- c(1980:1989)
the1990s <- c(1990:1999)

dataYears <- dataFrame %>% 
  mutate(groupYear = ifelse(grepl(paste(the1890s,collapse="|"), Year, ignore.case = TRUE), 1890, 
              ifelse(grepl(paste(the1900s,collapse="|"), Year, ignore.case = TRUE), 1900, 
              ifelse(grepl(paste(the1910s,collapse="|"), Year, ignore.case = TRUE), 1910, 
              ifelse(grepl(paste(the1920s,collapse="|"), Year, ignore.case = TRUE), 1920,
              ifelse(grepl(paste(the1930s,collapse="|"), Year, ignore.case = TRUE), 1930, 
              ifelse(grepl(paste(the1940s,collapse="|"), Year, ignore.case = TRUE), 1940,
              ifelse(grepl(paste(the1950s,collapse="|"), Year, ignore.case = TRUE), 1950,
              ifelse(grepl(paste(the1960s,collapse="|"), Year, ignore.case = TRUE), 1960,
              ifelse(grepl(paste(the1970s,collapse="|"), Year, ignore.case = TRUE), 1970,
              ifelse(grepl(paste(the1980s,collapse="|"), Year, ignore.case = TRUE), 1980,
              ifelse(grepl(paste(the1990s,collapse="|"), Year, ignore.case = TRUE), 1990, "???"))))))))))))


dataFilter <- dataYears %>% filter(column != 1) 

dataFoundRent <- dataFilter %>% mutate(rentDummy = ifelse(priceColumn == "rent", 1, 0)) %>% group_by(groupYear) %>% summarise(rentYearFound = sum(rentDummy))
dataFoundOwn <- dataFilter %>% mutate(ownDummy = ifelse(priceColumn == "sale", 1, 0)) %>% group_by(groupYear) %>% summarise(ownYearFound = sum(ownDummy))

df <- cbind.data.frame(dataFoundRent[,2], dataFoundOwn[,2], dataFoundRent[,2] + dataFoundOwn[,2])
colnames(df)[3] <- "yearObsTotalFound"
rownames(df) <- c(1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990)

return(df)
  
}
```



```{r}
test2 <- excelDataFound(dataMutc, dataMutc$Year, column = dataMutc$smallCoded, priceColumn = dataMutc$Price.type)
test2
```


Chicago 

#add everything with greater than 4 obseervations

```{r}
totalRentOrOwn(dataMutc, dataMutc$Year, priceColumn = dataMutc$Price.type)
excelDataFound(dataFrame = chicago, year = chicago$Year, column = chicago$smallCoded, priceColumn = chicago$Price.type)
```

New York

```{r}
totalRentOrOwn(newYorkExport, newYorkExport$Year, newYorkExport$Price.type)
excelDataFound(newYorkExport, newYorkExport$Year, newYorkExport$Coarse.Geo, newYorkExport$Price.type)
```

Boston 
 #use at least 5 obs 
```{r}
totalRentOrOwn(boston2, boston2$Year, boston2$Price.type)
excelData(boston2, boston2$Year, boston2$Area2, boston2$Price.type)
```

DC 

```{r}
totalRentOrOwn(excelDC, excelDC$Year, excelDC$Price.type)
excelData(excelDC, excelDC$Year, excelDC$Area2,excelDC$Price.type)
```

LA 

```{r}

```


